### ISSUE TITLE
Hello, have you uesd the 2D example (apparent resistivity and phase) in your paper to predict some simple examples such as some blocks with 100 Ωm background resistivity model?

### ISSUE THREAD

**Issue by liaoweiyang2017** [zhongpenggeo/EFNO#1]
When I used your trainning dataset to training, then used it to predict some simple cases (some blocks with 100   Ωm background resistivity model), but I found these results have huge error? Can you explain it at length?

**Comment by zhongpenggeo** [comment]
您好，很高兴你对这个研究感兴趣。
这个方法目前只适用于光滑连续地电结构。对于非连续地电结构，比如半空间模型中嵌入一些块状异常体的话，它的误差可能会比较大。这类模型中，我只测试过层状结构，预测精度还可以。如果你只对不连续地电结构感兴趣，可以考虑使用
U-Net架构，《A framework for data-driven solution and parameter estimation of
PDEs using conditional generative adversarial networks》这篇文章可能对你有帮助

**Comment by liaoweiyang2017** [comment]
好的，谢谢您，我去看看。
